### ISSUE TITLE
Add decimal separator

### ISSUE THREAD

**Issue by paolorotolo** [konaire/NumericKeyboard#1]
Please add the ability to use a decimal separator in the keyboard.

**Comment by paolorotolo** [comment]
A very dirty approach is available here: https://github.com/paolorotolo/NumericKeyboard/commit/18865e2aeda901d63527f91ba2263aa1e52e9b6d

I did it on a hurry because I needed it quick for a project, but we may think of allowing user to customize that "special" button or automatically use the correct decimal separator based on user locale.

**Comment by konaire** [comment]
Hey. Thank you for using this library. Unfortunately I don't have enough time right now. I'll try to add it on the next week.

**Comment by paolorotolo** [comment]
I'll try make a pull request maybe this days :)

**Comment by paolorotolo** [comment]
Probability fixed (with a more generic approach) in #4

**Comment by konaire** [comment]
Fixed in [1.0.5](https://github.com/konaire/NumericKeyboard/releases/tag/1.0.5)
