### ISSUE TITLE
Add modal bottom sheet behaviour

### ISSUE THREAD

**Issue by paolorotolo** [konaire/NumericKeyboard#5]
It would be nice to add a flag to make NumericKeyboard look like the default soft keyboard with the modal bottom sheet behaviour.

**Comment by konaire** [comment]
Sorry for such a late response. It's a great idea but unfortunately I don't think that it's doable here. The initial purpose of this library was to have it as simple as possible. So it means that the keyboard should stay on the screen all the time without an ability to show/hide it.
