### ISSUE TITLE
Move lib from jcenter

### ISSUE THREAD

**Issue by nfadhil13** [konaire/NumericKeyboard#8]
Would you move your library from JCenter please ? 
The JCenter repository is being shut down at the end of April, and as such Gradle needs to be updated to not depend on it any more and instead revert to mavenCentral()

https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

**Comment by dominikjambor** [comment]
@konaire ? 🥺

**Comment by konaire** [comment]
Sorry guys, I don't have time at the moment to migrate to maven. I'll try to migrate before December 2021. But JCenter [should be read only forever](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). So you should be able to access the library until migration is complete.
> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

**Comment by konaire** [comment]
Done: https://github.com/konaire/NumericKeyboard/releases/tag/1.2.0
